### ISSUE TITLE
Install throws error.

### ISSUE THREAD

**Issue by klenwell** [klenwell/neechy#16]
```
NEECHY CONSOLE ERROR:
$_SERVER["REQUEST_URI"] not found.
```

**Comment by klenwell** [comment]
Here's fix:

```
diff --git a/core/neechy/request.php b/core/neechy/request.php
index e7c2034..420e2bf 100644
--- a/core/neechy/request.php
+++ b/core/neechy/request.php
@@ -31,7 +31,9 @@ class NeechyRequest {
     # Constructor
     #
     public function __construct() {
-        if ( ! isset($_SERVER["REQUEST_URI"]) ) {
+        $in_console = ( php_sapi_name() == 'cli' );
+
+        if ( ! isset($_SERVER["REQUEST_URI"]) && ! $in_console ) {
             throw new NeechyRequestError('$_SERVER["REQUEST_URI"] not found.', 500);
         }
 
diff --git a/core/services/console.php b/core/services/console.php
index 333c1e8..7374811 100644
--- a/core/services/console.php
+++ b/core/services/console.php
@@ -96,9 +96,11 @@ class NeechyConsoleService extends NeechyService {
 NEECHY CONSOLE ERROR:
 %s
 
+%s
+
 
 STDERR;
-        $output = sprintf($format, $e->getMessage());
+        $output = sprintf($format, $e->getMessage(), $e->getTraceAsString());
         $response = NeechyResponse::stderr($output);
         return $response;
     }
```

**Comment by klenwell** [comment]
Here's the stack trace:

```
#0 /home/klenwell/projects/neechy-install/core/neechy/request.php(58): NeechyRequest->__construct()
#1 /home/klenwell/projects/neechy-install/core/neechy/templater.php(42): NeechyRequest::load()
#2 /home/klenwell/projects/neechy-install/core/neechy/templater.php(53): NeechyTemplater->__construct('bootstrap')
#3 /home/klenwell/projects/neechy-install/core/handlers/base.php(30): NeechyTemplater::load()
#4 /home/klenwell/projects/neechy-install/core/services/console.php(157): NeechyHandler->__construct()
#5 /home/klenwell/projects/neechy-install/core/services/console.php(87): NeechyConsoleService->load_handler()
#6 /home/klenwell/projects/neechy-install/core/services/console.php(54): NeechyConsoleService->dispatch_to_handler()
#7 /home/klenwell/projects/neechy-install/console/run.php(18): NeechyConsoleService->serve()
#8 {main}
```

Problem is request object requires a `$_SERVER["REQUEST_URI"]` even in console mode where it is not present.

The basic flow is:

`index.php` -> `Service` -> `Handler` -> `Templater` -> `Request`

This seems off. Let the `Service` generate the `Request` object. Then it can signal to the template what kind of response it wants and whether URL is needed.

**Comment by klenwell** [comment]
Successfully cloned repo, ran install script, and tested on local dev server.
